Fuentes:

https://arxiv.org/pdf/1607.00378.pdf   
https://github.com/chembl/chembl_webresource_client   
https://github.com/chembl/mychembl/blob/master/ipython_notebooks/09_myChEMBL_web_services.ipynb    
https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/tests.py    

Primero hay que pensar cómo se identifica un blanco:

- Nombre? Organismo?

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import urllib as urllib
import xmltodict as xmltodict
import sabueso as sab

In [3]:
#uniprot_id='P27540'
#uniprot_id='Q61221'
#uniprot_id='P97481'
#uniprot_id='Q16665'
#uniprot_id='Q99814'
uniprot_id='P53762'

url = 'http://www.uniprot.org/uniprot/'+uniprot_id+'.xml'

request = urllib.request.Request(url)
request.add_header('User-Agent', 'Python at https://github.com/uibcdf/MolInterrogator || prada.gracia@gmail.com')
response = urllib.request.urlopen(request)
xml_result = response.read().decode('utf-8')
dict_result = xmltodict.parse(xml_result)
dict_result = dict_result['uniprot']['entry']


In [4]:
pdb_id='4ZPR'
pdb_id='4ZPH'

aa = sab.PDB(pdb_id)

AttributeError: module 'sabueso' has no attribute 'PDB'

In [5]:
import pypdb as pypdb

In [18]:
all_info = pypdb.get_all_info('4ZPH')

In [19]:
description = pypdb.describe_pdb('4ZPH')

In [20]:
entity_info = pypdb.get_entity_info('4ZPH')

In [21]:
ligands_info = pypdb.get_ligands('4ZPH')

In [22]:
description

{'relatedPDB': [{'@pdbId': '4ZP4', '@details': ''},
  {'@pdbId': '4ZPK', '@details': ''},
  {'@pdbId': '4ZPR', '@details': ''}],
 'structureId': '4ZPH',
 'title': 'Crystal Structure of the Heterodimeric HIF-2a:ARNT Complex with Proflavine',
 'pubmedId': '26245371',
 'expMethod': 'X-RAY DIFFRACTION',
 'resolution': '2.80',
 'keywords': 'PROTEIN TRANSPORT/TRANSCRIPTION',
 'nr_entities': '2',
 'nr_residues': '1488',
 'nr_atoms': '8843',
 'deposition_date': '2015-05-07',
 'release_date': '2015-08-12',
 'last_modification_date': '2015-08-26',
 'structure_authors': 'Wu, D., Potluri, N., Lu, J., Kim, Y., Rastinejad, F.',
 'citation_authors': 'Wu, D., Potluri, N., Lu, J., Kim, Y., Rastinejad, F.',
 'status': 'CURRENT'}

In [23]:
all_info['polymer']

[{'@entityNr': '1',
  '@length': '384',
  '@type': 'protein',
  '@weight': '43437.4',
  'chain': [{'@id': 'A'}, {'@id': 'C'}],
  'Taxonomy': {'@name': 'Mus musculus', '@id': '10090'},
  'synonym': {'@name': 'ARNT protein, Dioxin receptor, nuclear translocator, Hypoxia-inducible factor 1-beta, HIF1-beta'},
  'macroMolecule': {'@name': 'Aryl hydrocarbon receptor nuclear translocator',
   'accession': {'@id': 'P53762'}},
  'polymerDescription': {'@description': 'Aryl hydrocarbon receptor nuclear translocator'},
  'fragment': {'@desc': 'UNP residues 82-464'}},
 {'@entityNr': '2',
  '@length': '360',
  '@type': 'protein',
  '@weight': '41201.0',
  'chain': [{'@id': 'B'}, {'@id': 'D'}],
  'Taxonomy': {'@name': 'Mus musculus', '@id': '10090'},
  'synonym': {'@name': 'EPAS-1, HIF-1-alpha-like factor, mHLF, HIF-related factor, HRF, Hypoxia-inducible factor 2-alpha, HIF2-alpha'},
  'macroMolecule': {'@name': 'Endothelial PAS domain-containing protein 1',
   'accession': {'@id': 'P97481'}},
  'po

In [24]:
entity_info

{'Method': {'@name': 'xray'},
 'Entity': [{'@id': '1',
   '@type': 'protein',
   'Chain': [{'@id': 'A'}, {'@id': 'C'}]},
  {'@id': '2', '@type': 'protein', 'Chain': [{'@id': 'B'}, {'@id': 'D'}]}],
 'structureId': '4ZPH',
 'bioAssemblies': '2',
 'release_date': 'Wed Aug 12 00:00:00 PDT 2015',
 'resolution': '2.80'}

In [31]:
ligands_info['ligandInfo']['ligand']

{'@structureId': '4ZPH',
 '@chemicalID': 'PRL',
 '@type': 'non-polymer',
 '@molecularWeight': '209.247',
 'chemicalName': 'PROFLAVIN',
 'formula': 'C13 H11 N3',
 'InChI': 'InChI=1S/C13H11N3/c14-10-3-1-8-5-9-2-4-11(15)7-13(9)16-12(8)6-10/h1-7H,14-15H2',
 'InChIKey': 'WDVSHHCDHLJJJR-UHFFFAOYSA-N',
 'smiles': 'c1cc(cc2c1cc3ccc(cc3n2)N)N'}

In [32]:
pypdb.describe_chemical('PRL')

{'describeHet': {'ligandInfo': {'ligand': {'@chemicalID': 'PRL',
    '@type': 'non-polymer',
    '@molecularWeight': '209.247',
    'chemicalName': 'PROFLAVIN',
    'formula': 'C13 H11 N3',
    'InChI': 'InChI=1S/C13H11N3/c14-10-3-1-8-5-9-2-4-11(15)7-13(9)16-12(8)6-10/h1-7H,14-15H2',
    'InChIKey': 'WDVSHHCDHLJJJR-UHFFFAOYSA-N',
    'smiles': 'c1cc(cc2c1cc3ccc(cc3n2)N)N'}}}}

In [33]:
pypdb.get_pfam('4ZPH')

{'pfamHit': [{'@structureId': '4ZPH',
   '@chainId': 'A',
   '@pdbResNumStart': '98',
   '@pdbResNumEnd': '142',
   '@pfamAcc': 'PF00010.25',
   '@pfamName': 'HLH',
   '@pfamDesc': 'Helix-loop-helix DNA-binding domain',
   '@eValue': '2.0E-15'},
  {'@structureId': '4ZPH',
   '@chainId': 'A',
   '@pdbResNumStart': '166',
   '@pdbResNumEnd': '269',
   '@pfamAcc': 'PF00989.24',
   '@pfamName': 'PAS',
   '@pfamDesc': 'PAS fold',
   '@eValue': '8.8E-24'},
  {'@structureId': '4ZPH',
   '@chainId': 'A',
   '@pdbResNumStart': '362',
   '@pdbResNumEnd': '462',
   '@pfamAcc': 'PF14598.5',
   '@pfamName': 'PAS_11',
   '@pfamDesc': 'PAS domain',
   '@eValue': '5.4E-23'},
  {'@structureId': '4ZPH',
   '@chainId': 'B',
   '@pdbResNumStart': '93',
   '@pdbResNumEnd': '173',
   '@pfamAcc': 'PF00989.24',
   '@pfamName': 'PAS',
   '@pfamDesc': 'PAS fold',
   '@eValue': '2.3E-15'},
  {'@structureId': '4ZPH',
   '@chainId': 'B',
   '@pdbResNumStart': '255',
   '@pdbResNumEnd': '341',
   '@pfamAcc': 'PF084

In [39]:
url = 'http://www.rcsb.org/pdb/rest/search'

queryText = """
<orgPdbQuery>
<queryType>org.pdb.query.simple.UpAccessionIdQuery</queryType>
<description>Simple query for a list of UniprotKB Accession IDs: P50225</description>
<accessionIdList>P50225</accessionIdList>
</orgPdbQuery>
"""


print("query:\n", queryText)

print("querying PDB...\n")

req = urllib.request.Request(url, data=queryText.encode())

f = urllib.request.urlopen(req)

result = f.read()

print(result)

query:
 
<orgPdbQuery>
<queryType>org.pdb.query.simple.UpAccessionIdQuery</queryType>
<description>Simple query for a list of UniprotKB Accession IDs: P50225</description>
<accessionIdList>P50225</accessionIdList>
</orgPdbQuery>

querying PDB...

b'1LS6:1\n1Z28:1\n2D06:1\n3QVU:1\n3QVV:1\n3U3J:1\n3U3K:1\n3U3M:1\n3U3O:1\n3U3R:1\n4GRA:1\n'


In [40]:
from mmtf import fetch

In [50]:
decoded_data = fetch('4ZPH')

In [51]:
print("PDB Code: "+str(decoded_data.structure_id)+" has "+str(decoded_data.num_chains)+" chains")

PDB Code: 4ZPH has 9 chains


In [52]:
print("Group name: "+str(decoded_data.group_list[0]["groupName"])+" has the following atomic charges: "+",".join([str(x) for x in decoded_data.group_list[0]["formalChargeList"]]))

Group name: VAL has the following atomic charges: 0,0,0,0,0,0,0


In [53]:
print("PDB Code: "+str(decoded_data.structure_id)+" has "+str(len(decoded_data.bio_assembly))+" bioassemblies")

PDB Code: 4ZPH has 2 bioassemblies


In [70]:
len(decoded_data.sec_struct_list)

1115

In [63]:
import mmtf as mmtf

In [68]:
decoded_data.chain_name_list

['A', 'B', 'C', 'D', 'A', 'A', 'B', 'C', 'D']

In [71]:
aaaa = fetch('4ZPH')

In [74]:
aaaa.

array([61.01, 64.43, 74.  , ..., 56.78, 38.14, 63.8 ])

In [79]:
sec_struct_codes = {0 : "I",
                    1 : "S",
                    2 : "H",
                    3 : "E",
                    4 : "G",
                    5 : "B",
                    6 : "T",
                    7 : "C",
                   -1 : "X"}

In [80]:
[sec_struct_codes[ii] for ii in aaaa.sec_struct_list]

['C',
 'C',
 'S',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'S',
 'H',
 'H',
 'H',
 'H',
 'T',
 'C',
 'S',
 'S',
 'C',
 'C',
 'C',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'C',
 'C',
 'C',
 'S',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'T',
 'C',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'T',
 'T',
 'T',
 'C',
 'B',
 'E',
 'E',
 'E',
 'E',
 'C',
 'G',
 'G',
 'H',
 'H',
 'H',
 'H',
 'H',
 'S',
 'C',
 'C',
 'G',
 'G',
 'G',
 'G',
 'T',
 'S',
 'C',
 'B',
 'H',
 'H',
 'H',
 'H',
 'B',
 'C',
 'G',
 'G',
 'G',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'T',
 'C',
 'C',
 'C',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'C',
 'C',
 'C',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'T',
 'T',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'C',
 'C',
 'C',
 'C',
 'C',
 'E',
 'E',
 'E',
 'E',
 'E',
 'E',
 'C',
 'T',
 'T',
 'C',
 'B',
 'E',
 'E',
 'E',
 'E',
 'C'

In [85]:
len(aaaa.group_list)

22

In [86]:
aaaa.groups_per_chain

[254, 292, 252, 294, 1, 10, 9, 1, 2]

In [87]:
aaaa.sequence_index_list

array([17, 18, 19, ..., -1, -1, -1])

In [90]:
len(aaaa.sequence_index_list)

1115

In [91]:
len(aaaa.sec_struct_list)

1115

In [93]:
len(aaaa.group_id_list)

1115

In [95]:
aaaa.group_id_list

array([ 98,  99, 100, ..., 501, 401, 402])

In [96]:
from Bio.PDB.mmtf import DefaultParser

In [99]:
help(DefaultParser.StructureDecoder)

Help on class StructureDecoder in module Bio.PDB.mmtf.DefaultParser:

class StructureDecoder(builtins.object)
 |  Class to pass the data from mmtf-python into a Biopython data structure.
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize the class.
 |  
 |  finalize_structure(self)
 |      Any functions needed to cleanup the structure.
 |  
 |  init_structure(self, total_num_bonds, total_num_atoms, total_num_groups, total_num_chains, total_num_models, structure_id)
 |      Initialize the structure object.
 |      
 |      :param total_num_bonds: the number of bonds in the structure
 |      :param total_num_atoms: the number of atoms in the structure
 |      :param total_num_groups: the number of groups in the structure
 |      :param total_num_chains: the number of chains in the structure
 |      :param total_num_models: the number of models in the structure
 |      :param structure_id: the id of the structure (e.g. PDB id)
 |  
 |  set_atom_info(self, atom_name,

In [115]:
def _get_seq_from_fasta_rcsb(pdb=None,chainId=None):


    url = 'https://www.rcsb.org/pdb/download/downloadFile.do?fileFormat=fastachain&compression=NO&structureId='+pdb+'&chainId='+chainId
    request = urllib.request.Request(url)
    response = urllib.request.urlopen(request)
    fasta_txt = response.read().decode('utf-8')

    return ''.join(fasta_txt.split('\n')[1:])

In [116]:
bb=_get_seq_from_fasta_rcsb('4ZPH','A')

In [117]:
bb

'MSSADKERLARENHSEIERRRRNKMTAYITELSDMVPTCSALARKPDKLTILRMAVSHMKSLRGTGNTSTDGSYKPSFLTDQELKHLILEAADGFLFIVSCETGRVVYVSDSVTPVLNQPQSEWFGSTLYDQVHPDDVDKLREQLSTSENALTGRVLDLKTGTVKKEGQQSSMRMCMGSRRSFICRMRCGTSSVDPVSMNRLSFLRNRCRNGLGSVKEGEPHFVVVHCTGYIKAWPPAGVSLPDDDPEAGQGSKFCLVAIGRLQVTSSPNCTDMSNICQPTEFISRHNIEGIFTFVDHRCVATVGYQPQELLGKNIVEFCHPEDQQLLRDSFQQVVKLKGQVLSVMFRFRSKTREWLWMRTSSFTFQNPYSDEIEYIICTNTNV'

In [120]:
aaaa.group_list

[{'groupName': 'VAL',
  'atomNameList': ['N', 'CA', 'C', 'O', 'CB', 'CG1', 'CG2'],
  'elementList': ['N', 'C', 'C', 'O', 'C', 'C', 'C'],
  'bondOrderList': [1, 1, 2, 1, 1, 1],
  'bondAtomList': [1, 0, 2, 1, 3, 2, 4, 1, 5, 4, 6, 4],
  'formalChargeList': [0, 0, 0, 0, 0, 0, 0],
  'singleLetterCode': 'V',
  'chemCompType': 'L-PEPTIDE LINKING'},
 {'groupName': 'LYS',
  'atomNameList': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'CE', 'NZ'],
  'elementList': ['N', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'N'],
  'bondOrderList': [1, 1, 2, 1, 1, 1, 1, 1],
  'bondAtomList': [1, 0, 2, 1, 3, 2, 4, 1, 5, 4, 6, 5, 7, 6, 8, 7],
  'formalChargeList': [0, 0, 0, 0, 0, 0, 0, 0, 1],
  'singleLetterCode': 'K',
  'chemCompType': 'L-PEPTIDE LINKING'},
 {'groupName': 'CYS',
  'atomNameList': ['N', 'CA', 'C', 'O', 'CB', 'SG'],
  'elementList': ['N', 'C', 'C', 'O', 'C', 'S'],
  'bondOrderList': [1, 1, 2, 1, 1],
  'bondAtomList': [1, 0, 2, 1, 3, 2, 4, 1, 5, 4],
  'formalChargeList': [0, 0, 0, 0, 0, 0],
  'singleLetterC

In [127]:
len(aaaa.group_type_list)

1115

In [135]:
aaaa.groups_per_chain

[254, 292, 252, 294, 1, 10, 9, 1, 2]

In [136]:
aaaa.group_id_list

array([ 98,  99, 100, ..., 501, 401, 402])

In [140]:
aaaa.group_type_list

array([15, 14, 14, ...,  3,  3,  3], dtype=int32)

In [147]:
aaaa.chain_name_list

['A', 'B', 'C', 'D', 'A', 'A', 'B', 'C', 'D']